// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package commonutils

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// PostMessageClient is the client API for PostMessage service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type PostMessageClient interface {
	SendMessage(ctx context.Context, in *MessageRequest, opts ...grpc.CallOption) (*MessageResponse, error)
}

type postMessageClient struct {
	cc grpc.ClientConnInterface
}

func NewPostMessageClient(cc grpc.ClientConnInterface) PostMessageClient {
	return &postMessageClient{cc}
}

func (c *postMessageClient) SendMessage(ctx context.Context, in *MessageRequest, opts ...grpc.CallOption) (*MessageResponse, error) {
	out := new(MessageResponse)
	err := c.cc.Invoke(ctx, "/commonutils.PostMessage/SendMessage", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PostMessageServer is the server API for PostMessage service.
// All implementations must embed UnimplementedPostMessageServer
// for forward compatibility
type PostMessageServer interface {
	SendMessage(context.Context, *MessageRequest) (*MessageResponse, error)
	mustEmbedUnimplementedPostMessageServer()
}

// UnimplementedPostMessageServer must be embedded to have forward compatible implementations.
type UnimplementedPostMessageServer struct {
}

func (UnimplementedPostMessageServer) SendMessage(context.Context, *MessageRequest) (*MessageResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SendMessage not implemented")
}
func (UnimplementedPostMessageServer) mustEmbedUnimplementedPostMessageServer() {}

// UnsafePostMessageServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PostMessageServer will
// result in compilation errors.
type UnsafePostMessageServer interface {
	mustEmbedUnimplementedPostMessageServer()
}

func RegisterPostMessageServer(s grpc.ServiceRegistrar, srv PostMessageServer) {
	s.RegisterService(&PostMessage_ServiceDesc, srv)
}

func _PostMessage_SendMessage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MessageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PostMessageServer).SendMessage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/commonutils.PostMessage/SendMessage",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PostMessageServer).SendMessage(ctx, req.(*MessageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// PostMessage_ServiceDesc is the grpc.ServiceDesc for PostMessage service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PostMessage_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "commonutils.PostMessage",
	HandlerType: (*PostMessageServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SendMessage",
			Handler:    _PostMessage_SendMessage_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "BotService.proto",
}
